baseURL = "/"
languageCode = "ja"
title = "naruブログ"
theme = "PaperMod"

paginate = 10

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[params.profileMode]
  enabled = true
  title = "naruブログ"
  subtitle = "投資と日常の第一次情報を投稿"
  imageUrl = "images/profile.jpg"   # プロフィール画像のパス
  imageWidth = 120
  imageHeight = 120
  imageTitle = "プロフィール画像"

